export const FETCH_BALANCES = 'FETCH_BALANCES';
export type FETCH_BALANCES = typeof FETCH_BALANCES;

export const FETCH_CURRENCIES_ID = 'FETCH_CURRENCIES_ID';
export type FETCH_CURRENCIES_ID = typeof FETCH_CURRENCIES_ID;

export const INCREASE_BALANCE = 'INCREASE_BALANCE';
export type INCREASE_BALANCE = typeof INCREASE_BALANCE;

export const DECREASE_BALANCE = 'DECREASE_BALANCE';
export type DECREASE_BALANCE = typeof DECREASE_BALANCE;
