export const FETCH_COMMENT = 'FETCH_COMMENT';
export type FETCH_COMMENT = typeof FETCH_COMMENT;

export const FILTER_COMMENT = 'FILTER_COMMENT';
export type FILTER_COMMENT = typeof FILTER_COMMENT;

export const SET_COMMENT_FILTER = 'SET_COMMENT_FILTER';
export type SET_COMMENT_FILTER = typeof SET_COMMENT_FILTER;

export const CLEAR_COMMENT = 'CLEAR_COMMENT';
export type CLEAR_COMMENT = typeof CLEAR_COMMENT;
