export const SET_TIPPED_POST = 'SET_TIPPED_POST';
export type SET_TIPPED_POST = typeof SET_TIPPED_POST;

export const CLEAR_TIPPED_POST = 'CLEAR_TIPPED_POST';
export type CLEAR_TIPPED_POST = typeof CLEAR_TIPPED_POST;

export const FETCH_TRANSACTION_HISTORY = 'FETCH_TRANSACTION_HISTORY';
export type FETCH_TRANSACTION_HISTORY = typeof FETCH_TRANSACTION_HISTORY;

export const FETCH_TRANSACTION_SUMMARY = 'FETCH_TRANSACTION_SUMMARY';
export type FETCH_TRANSACTION_SUMMARY = typeof FETCH_TRANSACTION_SUMMARY;
