export const SET_TIPPED_POST = 'SET_TIPPED_POST';
export type SET_TIPPED_POST = typeof SET_TIPPED_POST;

export const SET_TIPPED_COMMENT = 'SET_TIPPED_COMMENT';
export type SET_TIPPED_COMMENT = typeof SET_TIPPED_COMMENT;

export const CLEAR_TIPPED_CONTENT = 'CLEAR_TIPPED_CONTENT';
export type CLEAR_TIPPED_CONTENT = typeof CLEAR_TIPPED_CONTENT;

export const FETCH_TRANSACTION_HISTORY = 'FETCH_TRANSACTION_HISTORY';
export type FETCH_TRANSACTION_HISTORY = typeof FETCH_TRANSACTION_HISTORY;

export const FETCH_TRANSACTION_SUMMARY = 'FETCH_TRANSACTION_SUMMARY';
export type FETCH_TRANSACTION_SUMMARY = typeof FETCH_TRANSACTION_SUMMARY;

export const FETCH_TRANSACTION_HISTORY_FOR_COMMENT = 'FETCH_TRANSACTION_HISTORY_FOR_COMMENT';
export type FETCH_TRANSACTION_HISTORY_FOR_COMMENT = typeof FETCH_TRANSACTION_HISTORY_FOR_COMMENT;

export const FETCH_TRANSACTION_SUMMARY_FOR_COMMENT = 'FETCH_TRANSACTION_SUMMARY_FOR_COMMENT';
export type FETCH_TRANSACTION_SUMMARY_FOR_COMMENT = typeof FETCH_TRANSACTION_SUMMARY_FOR_COMMENT;
