export const FETCH_AVAILABLE_TOKEN = 'FETCH_AVAILABLE_TOKEN';
export type FETCH_AVAILABLE_TOKEN = typeof FETCH_AVAILABLE_TOKEN;

export const FETCH_PRIVACY_SETTING = 'FETCH_PRIVACY_SETTING';
export type FETCH_PRIVACY_SETTING = typeof FETCH_PRIVACY_SETTING;

export const UPDATE_NOTIFICATION_SETTING = 'UPDATE_NOTIFICATION_SETTING';
export type UPDATE_NOTIFICATION_SETTING = typeof UPDATE_NOTIFICATION_SETTING;
