export const FETCH_AVAILABLE_TOKEN = 'FETCH_AVAILABLE_TOKEN';
export type FETCH_AVAILABLE_TOKEN = typeof FETCH_AVAILABLE_TOKEN;

export const FETCH_FILTERED_TOKEN = 'FETCH_FILTERED_TOKEN';
export type FETCH_FILTERED_TOKEN = typeof FETCH_FILTERED_TOKEN;

export const FETCH_PRIVACY_SETTING = 'FETCH_PRIVACY_SETTING';
export type FETCH_PRIVACY_SETTING = typeof FETCH_PRIVACY_SETTING;

export const UPDATE_NOTIFICATION_SETTING = 'UPDATE_NOTIFICATION_SETTING';
export type UPDATE_NOTIFICATION_SETTING = typeof UPDATE_NOTIFICATION_SETTING;

export const SET_LANGUAGE_SETTING = 'SET_LANGUAGE_SETTING';
export type SET_LANGUAGE_SETTING = typeof SET_LANGUAGE_SETTING;

export const SET_LOADING_CONFIG = 'SET_LOADING_CONFIG';
export type SET_LOADING_CONFIG = typeof SET_LOADING_CONFIG;
