export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';
export type FETCH_NOTIFICATION = typeof FETCH_NOTIFICATION;

export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export type READ_NOTIFICATION = typeof READ_NOTIFICATION;

export const TOTAL_NEW_NOTIFICATION = 'TOTAL_NEW_NOTIFICATION';
export type TOTAL_NEW_NOTIFICATION = typeof TOTAL_NEW_NOTIFICATION;

export const CLEAR_NOTIFIACTION_COUNT = 'CLEAR_NOTIFIACTION_COUNT';
export type CLEAR_NOTIFIACTION_COUNT = typeof CLEAR_NOTIFIACTION_COUNT;

export const MARK_ALL_READ = 'MARK_ALL_READ';
export type MARK_ALL_READ = typeof MARK_ALL_READ;
