export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';
export type FETCH_NOTIFICATION = typeof FETCH_NOTIFICATION;

export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export type READ_NOTIFICATION = typeof READ_NOTIFICATION;

export const TOTAL_NEW_NOTIFICATION = 'TOTAL_NEW_NOTIFICATION';
export type TOTAL_NEW_NOTIFICATION = typeof TOTAL_NEW_NOTIFICATION;
