export const FETCH_NOTIFICATIION = 'FETCH_NOTIFICATIION';
export type FETCH_NOTIFICATIION = typeof FETCH_NOTIFICATIION;

export const READ_NOTIFICATIION = 'READ_NOTIFICATIION';
export type READ_NOTIFICATIION = typeof READ_NOTIFICATIION;
