export const FETCH_FRIEND = 'FETCH_FRIEND';
export type FETCH_FRIEND = typeof FETCH_FRIEND;

export const FETCH_FRIEND_REQUEST = 'FETCH_FRIEND_REQUEST';
export type FETCH_FRIEND_REQUEST = typeof FETCH_FRIEND_REQUEST;

export const CRETE_FRIEND_REQUEST = 'CRETE_FRIEND_REQUEST';
export type CRETE_FRIEND_REQUEST = typeof CRETE_FRIEND_REQUEST;

export const APPROVE_FRIEND_REQUEST = 'APPROVE_FRIEND_REQUEST';
export type APPROVE_FRIEND_REQUEST = typeof APPROVE_FRIEND_REQUEST;

export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST';
export type REJECT_FRIEND_REQUEST = typeof REJECT_FRIEND_REQUEST;
