export const FETCH_FRIEND = 'FETCH_FRIEND';
export type FETCH_FRIEND = typeof FETCH_FRIEND;

export const FETCH_FRIEND_REQUEST = 'FETCH_FRIEND_REQUEST';
export type FETCH_FRIEND_REQUEST = typeof FETCH_FRIEND_REQUEST;

export const CREATE_FRIEND_REQUEST = 'CREATE_FRIEND_REQUEST';
export type CREATE_FRIEND_REQUEST = typeof CREATE_FRIEND_REQUEST;

export const APPROVE_FRIEND_REQUEST = 'APPROVE_FRIEND_REQUEST';
export type APPROVE_FRIEND_REQUEST = typeof APPROVE_FRIEND_REQUEST;

export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST';
export type REJECT_FRIEND_REQUEST = typeof REJECT_FRIEND_REQUEST;

export const FILTER_FRIEND = 'FILTER_FRIEND';
export type FILTER_FRIEND = typeof FILTER_FRIEND;
