export const RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
export type RESET_SEARCH_STATE = typeof RESET_SEARCH_STATE;

export const LOAD_USERS = 'LOAD_USERS';
export type LOAD_USERS = typeof LOAD_USERS;

export const LOAD_SEARCHED_USERS = 'LOAD_SEARCHED_USERS';
export type LOAD_SEARCHED_USERS = typeof LOAD_SEARCHED_USERS;

export const SEARCH_USERS = 'SEARCH_USERS';
export type SEARCH_USERS = typeof SEARCH_USERS;

export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS';
export type SET_SEARCHED_USERS = typeof SET_SEARCHED_USERS;

export const ABORT_SEARCH = 'ABORT_SEARCH';
export type ABORT_SEARCH = typeof ABORT_SEARCH;

export const USERS_LOADING = 'USERS_LOADING';
export type USERS_LOADING = typeof USERS_LOADING;
