export const RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
export type RESET_SEARCH_STATE = typeof RESET_SEARCH_STATE;

export const SEARCH_USERS = 'SEARCH_USERS';
export type SEARCH_USERS = typeof SEARCH_USERS;

export const ABORT_SEARCH = 'ABORT_SEARCH';
export type ABORT_SEARCH = typeof ABORT_SEARCH;
