export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export type FETCH_TRANSACTIONS = typeof FETCH_TRANSACTIONS;

export const SET_TRANSACTION_FILTER = 'SET_TRANSACTION_FILTER';
export type SET_TRANSACTION_FILTER = typeof SET_TRANSACTION_FILTER;

export const SET_TRANSACTION_SORT = 'SET_TRANSACTION_SORT';
export type SET_TRANSACTION_SORT = typeof SET_TRANSACTION_SORT;

export const SET_TRANSACTION_LOADING = 'SET_TRANSACTION_LOADING';
export type SET_TRANSACTION_LOADING = typeof SET_TRANSACTION_LOADING;
