export const FETCH_ALL_EXPERIENCES = 'FETCH_ALL_EXPERIENCES';
export type FETCH_ALL_EXPERIENCES = typeof FETCH_ALL_EXPERIENCES;

export const FETCH_EXPERIENCE = 'FETCH_EXPERIENCE';
export type FETCH_EXPERIENCE = typeof FETCH_EXPERIENCE;

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export type ADD_EXPERIENCE = typeof ADD_EXPERIENCE;

export const SELECT_EXPERIENCE = 'SELECT_EXPERIENCE';
export type SELECT_EXPERIENCE = typeof SELECT_EXPERIENCE;

export const UPDATE_SELECTED_EXPERIENCE = 'UPDATE_SELECTED_EXPERIENCE';
export type UPDATE_SELECTED_EXPERIENCE = typeof UPDATE_SELECTED_EXPERIENCE;

export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export type REMOVE_EXPERIENCE = typeof REMOVE_EXPERIENCE;

export const LOAD_SEARCHED_EXPERIENCES = 'LOAD_SEARCHED_EXPERIENCES';
export type LOAD_SEARCHED_EXPERIENCES = typeof LOAD_SEARCHED_EXPERIENCES;

export const SEARCH_ALL_RELATED_EXPERIENCES = 'SEARCH_ALL_RELATED_EXPERIENCES';
export type SEARCH_ALL_RELATED_EXPERIENCES = typeof SEARCH_ALL_RELATED_EXPERIENCES;

export const SEARCH_EXPERIENCE = 'SEARCH_EXPERIENCE';
export type SEARCH_EXPERIENCE = typeof SEARCH_EXPERIENCE;

export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export type SEARCH_PEOPLE = typeof SEARCH_PEOPLE;

export const SEARCH_TAGS = 'SEARCH_TAGS';
export type SEARCH_TAGS = typeof SEARCH_TAGS;

export const FETCH_DETAIL_EXPERIENCE = 'FETCH_DETAIL_EXPERIENCE';
export type FETCH_DETAIL_EXPERIENCE = typeof FETCH_DETAIL_EXPERIENCE;

export const EXPERIENCE_LOADING = 'EXPERIENCE_LOADING';
export type EXPERIENCE_LOADING = typeof EXPERIENCE_LOADING;
