export const FETCH_EXPERIENCE = 'FETCH_EXPERIENCE';
export type FETCH_EXPERIENCE = typeof FETCH_EXPERIENCE;

export const SEARCH_EXPERIENCE = 'SEARCH_EXPERIENCE';
export type SEARCH_EXPERIENCE = typeof SEARCH_EXPERIENCE;

export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export type SEARCH_PEOPLE = typeof SEARCH_PEOPLE;

export const SEARCH_TAGS = 'SEARCH_TAGS';
export type SEARCH_TAGS = typeof SEARCH_TAGS;
