export const FETCH_RECIPIENT_DETAIL = 'FETCH_RECIPIENT_DETAIL';
export type FETCH_RECIPIENT_DETAIL = typeof FETCH_RECIPIENT_DETAIL;

export const SET_RECIPIENT_DETAIL = 'SET_RECIPIENT_DETAIL';
export type SET_RECIPIENT_DETAIL = typeof SET_RECIPIENT_DETAIL;

export const SET_TIPPED_USER_ID = 'SET_TIPPED_USER_ID';
export type SET_TIPPED_USER_ID = typeof SET_TIPPED_USER_ID;

export const SET_TIPPED_USER = 'SET_TIPPED_USER';
export type SET_TIPPED_USER = typeof SET_TIPPED_USER;

export const SET_IS_TIP_SENT = 'SET_IS_TIP_SENT';
export type SET_IS_TIP_SENT = typeof SET_IS_TIP_SENT;

export const SET_FEE = 'SET_FEE';
export type SET_FEE = typeof SET_FEE;
