export const FETCH_RECIPIENT_DETAIL = 'FETCH_RECIPIENT_DETAIL';
export type FETCH_RECIPIENT_DETAIL = typeof FETCH_RECIPIENT_DETAIL;

export const SET_RECIPIENT_DETAIL = 'SET_RECIPIENT_DETAIL';
export type SET_RECIPIENT_DETAIL = typeof SET_RECIPIENT_DETAIL;
