export const FETCH_PROFILE_DETAIL = 'FETCH_PROFILE_DETAIL';
export type FETCH_PROFILE_DETAIL = typeof FETCH_PROFILE_DETAIL;

export const FETCH_PROFILE_FRIEND = 'FETCH_PROFILE_FRIEND';
export type FETCH_PROFILE_FRIEND = typeof FETCH_PROFILE_FRIEND;

export const FILTER_PROFILE_FRIEND = 'FILTER_PROFILE_FRIEND';
export type FILTER_PROFILE_FRIEND = typeof FILTER_PROFILE_FRIEND;

export const FETCH_PROFILE_SOCIALS = 'FETCH_PROFILE_SOCIALS';
export type FETCH_PROFILE_SOCIALS = typeof FETCH_PROFILE_SOCIALS;

export const FETCH_PROFILE_EXPERIENCE = 'FETCH_PROFILE_EXPERIENCE';
export type FETCH_PROFILE_EXPERIENCE = typeof FETCH_PROFILE_EXPERIENCE;

export const SET_FRIENDED_STATUS = 'SET_FRIENDED_STATUS';
export type SET_FRIENDED_STATUS = typeof SET_FRIENDED_STATUS;

export const CLEAR_FRIENDED_STATUS = 'CLEAR_FRIENDED_STATUS';
export type CLEAR_FRIENDED_STATUS = typeof CLEAR_FRIENDED_STATUS;

export const SORT_PROFILE_FRIENDS = 'SORT_PROFILE_FRIENDS';
export type SORT_PROFILE_FRIENDS = typeof SORT_PROFILE_FRIENDS;

export const SET_PROFILE_FRIENDS_FILTER = 'SET_PROFILE_FRIENDS_FILTER';
export type SET_PROFILE_FRIENDS_FILTER = typeof SET_PROFILE_FRIENDS_FILTER;
