export const FETCH_PROFILE_DETAIL = 'FETCH_PROFILE_DETAIL';
export type FETCH_PROFILE_DETAIL = typeof FETCH_PROFILE_DETAIL;

export const FETCH_PROFILE_FRIEND = 'FETCH_PROFILE_FRIEND';
export type FETCH_PROFILE_FRIEND = typeof FETCH_PROFILE_FRIEND;

export const FILTER_PROFILE_FRIEND = 'FILTER_PROFILE_FRIEND';
export type FILTER_PROFILE_FRIEND = typeof FILTER_PROFILE_FRIEND;

export const FETCH_PROFILE_SOCIALS = 'FETCH_PROFILE_SOCIALS';
export type FETCH_PROFILE_SOCIALS = typeof FETCH_PROFILE_SOCIALS;
