export const SET_EXCLUSIVE_CONTENT_ID = 'SET_EXCLUSIVE_CONTENT_ID';
export type SET_EXCLUSIVE_CONTENT_ID = typeof SET_EXCLUSIVE_CONTENT_ID;

export const PAID_EXCLUSIVE_CONTENT = 'PAID_EXCLUSIVE_CONTENT';
export type PAID_EXCLUSIVE_CONTENT = typeof PAID_EXCLUSIVE_CONTENT;
