export const SHOW_TOASTER_SNACK = 'SHOW_TOASTER_SNACK';
export type SHOW_TOASTER_SNACK = typeof SHOW_TOASTER_SNACK;

export const CLOSE_TOASTER_SNACK = 'CLOSE_TOASTER_SNACK';
export type CLOSE_TOASTER_SNACK = typeof CLOSE_TOASTER_SNACK;

export const STORE_DISPLAYED_TOAST_SNACK = 'STORE_DISPLAYED_TOAST_SNACK';
export type STORE_DISPLAYED_TOAST_SNACK = typeof STORE_DISPLAYED_TOAST_SNACK;

export const CLEAR_DISPLAYED_TOAST_SNACK = 'CLEAR_DISPLAYED_TOAST_SNACK';
export type CLEAR_DISPLAYED_TOAST_SNACK = typeof CLEAR_DISPLAYED_TOAST_SNACK;
