export const FETCH_USER = 'FETCH_USER';
export type FETCH_USER = typeof FETCH_USER;

export const FETCH_USER_TOKEN = 'FETCH_USER_TOKEN';
export type FETCH_USER_TOKEN = typeof FETCH_USER_TOKEN;

export const ADD_USER_TOKEN = 'ADD_USER_TOKEN';
export type ADD_USER_TOKEN = typeof ADD_USER_TOKEN;

export const SET_DEFAULT_CURRENCY = 'SET_DEFAULT_CURRENCY';
export type SET_DEFAULT_CURRENCY = typeof SET_DEFAULT_CURRENCY;

export const FETCH_USER_SOCIALS = 'FETCH_USER_SOCIALS';
export type FETCH_USER_SOCIALS = typeof FETCH_USER_SOCIALS;

export const FETCH_USER_EXPERIENCE = 'FETCH_USER_EXPERIENCE';
export type FETCH_USER_EXPERIENCE = typeof FETCH_USER_EXPERIENCE;

export const FETCH_CURRENT_USER_WALLETS = 'FETCH_CURRENT_USER_WALLETS';
export type FETCH_CURRENT_USER_WALLETS = typeof FETCH_CURRENT_USER_WALLETS;

export const FETCH_USER_WALLETS = 'FETCH_USER_WALLETS';
export type FETCH_USER_WALLETS = typeof FETCH_USER_WALLETS;

export const FETCH_USER_TRANSACTION_DETAIL = 'FETCH_USER_TRANSACTION_DETAIL';
export type FETCH_USER_TRANSACTION_DETAIL = typeof FETCH_USER_TRANSACTION_DETAIL;

export const SET_USER_AS_ANONYMOUS = 'SET_USER_AS_ANONYMOUS';
export type SET_USER_AS_ANONYMOUS = typeof SET_USER_AS_ANONYMOUS;

export const UPDATE_USER = 'UPDATE_USER';
export type UPDATE_USER = typeof UPDATE_USER;

export const SET_VERIFYING_SOCIAL_ACCOUNT = 'SET_VERIFYING_SOCIAL_ACCOUNT';
export type SET_VERIFYING_SOCIAL_ACCOUNT = typeof SET_VERIFYING_SOCIAL_ACCOUNT;

export const RESET_VERIFYING_SOCIAL_ACCOUNT = 'RESET_VERIFYING_SOCIAL_ACCOUNT';
export type RESET_VERIFYING_SOCIAL_ACCOUNT = typeof RESET_VERIFYING_SOCIAL_ACCOUNT;

export const CLEAR_USER = 'CLEAR_USER';
export type CLEAR_USER = typeof CLEAR_USER;
