export const FETCH_USER = 'FETCH_USER';
export type FETCH_USER = typeof FETCH_USER;

export const FETCH_USER_TOKEN = 'FETCH_USER_TOKEN';
export type FETCH_USER_TOKEN = typeof FETCH_USER_TOKEN;

export const FETCH_USER_TRANSACTION_DETAILS = 'FETCH_USER_TRANSACTION_DETAILS';
export type FETCH_USER_TRANSACTION_DETAILS = typeof FETCH_USER_TRANSACTION_DETAILS;

export const SET_USER_AS_ANONYMOUS = 'SET_USER_AS_ANONYMOUS';
export type SET_USER_AS_ANONYMOUS = typeof SET_USER_AS_ANONYMOUS;

export const UPDATE_USER = 'UPDATE_USER';
export type UPDATE_USER = typeof UPDATE_USER;

export const FETCH_RECIPIENT_DETAIL = 'FETCH_RECIPIENT_DETAIL';
export type FETCH_RECIPIENT_DETAIL = typeof FETCH_RECIPIENT_DETAIL;

export const SET_RECIPIENT_DETAIL = 'SET_RECIPIENT_DETAIL';
export type SET_RECIPIENT_DETAIL = typeof SET_RECIPIENT_DETAIL;

export const SET_VERIFYING_SOCIAL_ACCOUNT = 'SET_VERIFYING_SOCIAL_ACCOUNT';
export type SET_VERIFYING_SOCIAL_ACCOUNT = typeof SET_VERIFYING_SOCIAL_ACCOUNT;

export const RESET_VERIFYING_SOCIAL_ACCOUNT = 'RESET_VERIFYING_SOCIAL_ACCOUNT';
export type RESET_VERIFYING_SOCIAL_ACCOUNT = typeof RESET_VERIFYING_SOCIAL_ACCOUNT;
